env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
    - omitLastInOneLineBlock: true
  no-multiple-empty-lines:
  - error
  - max: 2
    maxEOF: 1
  max-len:
  - 2
  - 120
  - 4
  - ignoreUrls: true
  curly:
  - error
  - multi-or-nest
  comma-dangle:
  - error
  - never
  no-throw-literal: 'off'
  no-return-await: warn
  consistent-return: warn
  no-use-before-define: 'off'
  max-lines-per-function:
  - error
  - 100
  max-params:
  - error
  - 8
  no-unsafe-finally: 'off'
  no-undef: 'off'
